# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "https://dev.odgn.net"

# Basic metadata configuration for your blog.
title = 'ODGN Dev'
author = "Alex Veenendaal"
copyright = "Copyright © 2024, Alex Veenendaal."
languageCode = "en-US"


theme = 'hugo-bearblog'


[params]

    # This theme will, by default, inject a made-with-line at the bottom of the page.
    # You can turn it off, but we would really appreciate if you don’t :-).
    hideMadeWithLine = true