baseurl = "/"
title = "ODGN Dev"
copyright = "Copyright (c) 2024, all rights reserved."
canonifyurls = true
languageCode = "en-US"
paginate = 3
theme = "hugo-dusk"

googleAnalytics = ""
disqusShortname = ""

[params.author]
  name = "Alex Veenendaal"

SectionPagesMenu = "main"

# Configure syntax highlight
[markup]
  [markup.highlight]
    style = "gruvbox"  # dark themes: monokai, api, fruity, native, rrt, swapoff ... https://xyproto.github.io/splash/docs/longer/all.html
  [markup.goldmark]
  [markup.goldmark.renderer]
unsafe= true
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[params.meta]
  keywords = "blog, tech"
  description = "Dev blog."

[params]
  github = "odogono"
  twitter = "odogono"
  email = "alex@opendoorgonorth.com"
  theme_colors = "default-dark" # uses color css file under static/css/default-dark.css