baseurl = "/"
canonifyurls = true
copyright = "Copyright (c) 2025, all rights reserved."
languageCode = "en-GB"
theme = "hugo-dusk"
title = "ODGN Dev"

disqusShortname = ""
googleAnalytics = ""

[params.author]
name = "Alex Veenendaal"

SectionPagesMenu = "main"

[pagination]
pagerSize = 10

# Configure syntax highlight
[markup]
[markup.highlight]
style = "gruvbox"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.renderHooks]
[markup.goldmark.renderHooks.image]
enableDefault = true

[[menu.main]]
identifier = "post"
name = "Posts"
url = "/posts/"
weight = -120

[[menu.main]]
identifier = "tag"
name = "Tags"
url = "/tags/"
weight = -110

[params.meta]
description = "Dev blog."
keywords = "blog, tech"

[params]
bluesky = "https://bsky.app/profile/alex.veenenda.al" 
github = "odogono" 
linkedin = "alexanderveenendaal" 
theme_colors = "default-dark" # uses color css file under static/css/default-dark.css
twitter = "odogono"
